/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as publicSignUpIndexRouteImport } from './routes/(public)/sign-up/index'
import { Route as publicSignInIndexRouteImport } from './routes/(public)/sign-in/index'
import { Route as privateClansIndexRouteImport } from './routes/(private)/clans/index'
import { Route as privateWarsClanTagRouteImport } from './routes/(private)/wars/$clanTag'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const publicSignUpIndexRoute = publicSignUpIndexRouteImport.update({
  id: '/(public)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInIndexRoute = publicSignInIndexRouteImport.update({
  id: '/(public)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateClansIndexRoute = privateClansIndexRouteImport.update({
  id: '/clans/',
  path: '/clans/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateWarsClanTagRoute = privateWarsClanTagRouteImport.update({
  id: '/wars/$clanTag',
  path: '/wars/$clanTag',
  getParentRoute: () => privateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/wars/$clanTag': typeof privateWarsClanTagRoute
  '/clans': typeof privateClansIndexRoute
  '/sign-in': typeof publicSignInIndexRoute
  '/sign-up': typeof publicSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/wars/$clanTag': typeof privateWarsClanTagRoute
  '/clans': typeof privateClansIndexRoute
  '/sign-in': typeof publicSignInIndexRoute
  '/sign-up': typeof publicSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/(private)': typeof privateRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(private)/wars/$clanTag': typeof privateWarsClanTagRoute
  '/(private)/clans/': typeof privateClansIndexRoute
  '/(public)/sign-in/': typeof publicSignInIndexRoute
  '/(public)/sign-up/': typeof publicSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wars/$clanTag' | '/clans' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wars/$clanTag' | '/clans' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/(home)'
    | '/(private)'
    | '/(home)/'
    | '/(private)/wars/$clanTag'
    | '/(private)/clans/'
    | '/(public)/sign-in/'
    | '/(public)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicSignInIndexRoute: typeof publicSignInIndexRoute
  publicSignUpIndexRoute: typeof publicSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(public)/sign-up/': {
      id: '/(public)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in/': {
      id: '/(public)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/clans/': {
      id: '/(private)/clans/'
      path: '/clans'
      fullPath: '/clans'
      preLoaderRoute: typeof privateClansIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/wars/$clanTag': {
      id: '/(private)/wars/$clanTag'
      path: '/wars/$clanTag'
      fullPath: '/wars/$clanTag'
      preLoaderRoute: typeof privateWarsClanTagRouteImport
      parentRoute: typeof privateRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeIndexRoute: homeIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface privateRouteRouteChildren {
  privateWarsClanTagRoute: typeof privateWarsClanTagRoute
  privateClansIndexRoute: typeof privateClansIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateWarsClanTagRoute: privateWarsClanTagRoute,
  privateClansIndexRoute: privateClansIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicSignInIndexRoute: publicSignInIndexRoute,
  publicSignUpIndexRoute: publicSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
